title: Polskie Towarzystwo Urologiczne
subtitle: Oddział Dolnośląski
email: ptudolnyslask@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Strona Oddziału dolnośląskiego Polskiego Towarzystwa Urologicznego
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ptudolnyslask.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  style: compressed

contact_mail: ptudolnyslask(at)gmail.pl

exclude:
  - README.md
